/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as MacInstallRouteImport } from './routes/mac-install'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VTokenRouteImport } from './routes/v/$token'
import { Route as ShareFileIdRouteImport } from './routes/share.$fileId'
import { Route as MainAdminRouteImport } from './routes/main/admin'
import { Route as DashboardWithdrawRouteImport } from './routes/dashboard/withdraw'
import { Route as DashboardUploadRouteImport } from './routes/dashboard/upload'
import { Route as DashboardSupportRouteImport } from './routes/dashboard/support'
import { Route as DashboardSettingsPageRouteImport } from './routes/dashboard/settings-page'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard/referrals'
import { Route as DashboardFilesRouteImport } from './routes/dashboard/files'
import { Route as DashboardEarningsRouteImport } from './routes/dashboard/earnings'
import { Route as DashboardApiKeyRouteImport } from './routes/dashboard/api-key'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTicketsRouteImport } from './routes/admin/tickets'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminStorageRouteImport } from './routes/admin/storage'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminPayoutsRouteImport } from './routes/admin/payouts'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminFilesRouteImport } from './routes/admin/files'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminUserIdRouteImport } from './routes/admin/user.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const MacInstallRoute = MacInstallRouteImport.update({
  id: '/mac-install',
  path: '/mac-install',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VTokenRoute = VTokenRouteImport.update({
  id: '/v/$token',
  path: '/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareFileIdRoute = ShareFileIdRouteImport.update({
  id: '/share/$fileId',
  path: '/share/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const MainAdminRoute = MainAdminRouteImport.update({
  id: '/main/admin',
  path: '/main/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWithdrawRoute = DashboardWithdrawRouteImport.update({
  id: '/dashboard/withdraw',
  path: '/dashboard/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/dashboard/upload',
  path: '/dashboard/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/dashboard/support',
  path: '/dashboard/support',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsPageRoute = DashboardSettingsPageRouteImport.update({
  id: '/dashboard/settings-page',
  path: '/dashboard/settings-page',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/dashboard/referrals',
  path: '/dashboard/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFilesRoute = DashboardFilesRouteImport.update({
  id: '/dashboard/files',
  path: '/dashboard/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEarningsRoute = DashboardEarningsRouteImport.update({
  id: '/dashboard/earnings',
  path: '/dashboard/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardApiKeyRoute = DashboardApiKeyRouteImport.update({
  id: '/dashboard/api-key',
  path: '/dashboard/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/admin/tickets',
  path: '/admin/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/admin/storage',
  path: '/admin/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFilesRoute = AdminFilesRouteImport.update({
  id: '/admin/files',
  path: '/admin/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserIdRoute = AdminUserIdRouteImport.update({
  id: '/admin/user/$id',
  path: '/admin/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/mac-install': typeof MacInstallRoute
  '/payouts': typeof PayoutsRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/report': typeof ReportRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/api-key': typeof DashboardApiKeyRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/settings-page': typeof DashboardSettingsPageRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/withdraw': typeof DashboardWithdrawRoute
  '/main/admin': typeof MainAdminRoute
  '/share/$fileId': typeof ShareFileIdRoute
  '/v/$token': typeof VTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/user/$id': typeof AdminUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/mac-install': typeof MacInstallRoute
  '/payouts': typeof PayoutsRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/report': typeof ReportRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/api-key': typeof DashboardApiKeyRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/settings-page': typeof DashboardSettingsPageRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/withdraw': typeof DashboardWithdrawRoute
  '/main/admin': typeof MainAdminRoute
  '/share/$fileId': typeof ShareFileIdRoute
  '/v/$token': typeof VTokenRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/user/$id': typeof AdminUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/mac-install': typeof MacInstallRoute
  '/payouts': typeof PayoutsRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/report': typeof ReportRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/api-key': typeof DashboardApiKeyRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/settings-page': typeof DashboardSettingsPageRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/withdraw': typeof DashboardWithdrawRoute
  '/main/admin': typeof MainAdminRoute
  '/share/$fileId': typeof ShareFileIdRoute
  '/v/$token': typeof VTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/user/$id': typeof AdminUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/download'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/mac-install'
    | '/payouts'
    | '/privacy'
    | '/rates'
    | '/report'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/files'
    | '/admin/messages'
    | '/admin/payouts'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/users'
    | '/dashboard/api-key'
    | '/dashboard/earnings'
    | '/dashboard/files'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/settings-page'
    | '/dashboard/support'
    | '/dashboard/upload'
    | '/dashboard/withdraw'
    | '/main/admin'
    | '/share/$fileId'
    | '/v/$token'
    | '/admin/'
    | '/dashboard/'
    | '/admin/user/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/download'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/mac-install'
    | '/payouts'
    | '/privacy'
    | '/rates'
    | '/report'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/files'
    | '/admin/messages'
    | '/admin/payouts'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/users'
    | '/dashboard/api-key'
    | '/dashboard/earnings'
    | '/dashboard/files'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/settings-page'
    | '/dashboard/support'
    | '/dashboard/upload'
    | '/dashboard/withdraw'
    | '/main/admin'
    | '/share/$fileId'
    | '/v/$token'
    | '/admin'
    | '/dashboard'
    | '/admin/user/$id'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/download'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/mac-install'
    | '/payouts'
    | '/privacy'
    | '/rates'
    | '/report'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/files'
    | '/admin/messages'
    | '/admin/payouts'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/users'
    | '/dashboard/api-key'
    | '/dashboard/earnings'
    | '/dashboard/files'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/settings-page'
    | '/dashboard/support'
    | '/dashboard/upload'
    | '/dashboard/withdraw'
    | '/main/admin'
    | '/share/$fileId'
    | '/v/$token'
    | '/admin/'
    | '/dashboard/'
    | '/admin/user/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MacInstallRoute: typeof MacInstallRoute
  PayoutsRoute: typeof PayoutsRoute
  PrivacyRoute: typeof PrivacyRoute
  RatesRoute: typeof RatesRoute
  ReportRoute: typeof ReportRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminFilesRoute: typeof AdminFilesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStorageRoute: typeof AdminStorageRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DashboardApiKeyRoute: typeof DashboardApiKeyRoute
  DashboardEarningsRoute: typeof DashboardEarningsRoute
  DashboardFilesRoute: typeof DashboardFilesRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSettingsPageRoute: typeof DashboardSettingsPageRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardWithdrawRoute: typeof DashboardWithdrawRoute
  MainAdminRoute: typeof MainAdminRoute
  ShareFileIdRoute: typeof ShareFileIdRoute
  VTokenRoute: typeof VTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AdminUserIdRoute: typeof AdminUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mac-install': {
      id: '/mac-install'
      path: '/mac-install'
      fullPath: '/mac-install'
      preLoaderRoute: typeof MacInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$token': {
      id: '/v/$token'
      path: '/v/$token'
      fullPath: '/v/$token'
      preLoaderRoute: typeof VTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$fileId': {
      id: '/share/$fileId'
      path: '/share/$fileId'
      fullPath: '/share/$fileId'
      preLoaderRoute: typeof ShareFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/admin': {
      id: '/main/admin'
      path: '/main/admin'
      fullPath: '/main/admin'
      preLoaderRoute: typeof MainAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/withdraw': {
      id: '/dashboard/withdraw'
      path: '/dashboard/withdraw'
      fullPath: '/dashboard/withdraw'
      preLoaderRoute: typeof DashboardWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/dashboard/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/dashboard/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings-page': {
      id: '/dashboard/settings-page'
      path: '/dashboard/settings-page'
      fullPath: '/dashboard/settings-page'
      preLoaderRoute: typeof DashboardSettingsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/dashboard/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/files': {
      id: '/dashboard/files'
      path: '/dashboard/files'
      fullPath: '/dashboard/files'
      preLoaderRoute: typeof DashboardFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/earnings': {
      id: '/dashboard/earnings'
      path: '/dashboard/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof DashboardEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/api-key': {
      id: '/dashboard/api-key'
      path: '/dashboard/api-key'
      fullPath: '/dashboard/api-key'
      preLoaderRoute: typeof DashboardApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/storage': {
      id: '/admin/storage'
      path: '/admin/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/files': {
      id: '/admin/files'
      path: '/admin/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AdminFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/$id': {
      id: '/admin/user/$id'
      path: '/admin/user/$id'
      fullPath: '/admin/user/$id'
      preLoaderRoute: typeof AdminUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MacInstallRoute: MacInstallRoute,
  PayoutsRoute: PayoutsRoute,
  PrivacyRoute: PrivacyRoute,
  RatesRoute: RatesRoute,
  ReportRoute: ReportRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminFilesRoute: AdminFilesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStorageRoute: AdminStorageRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DashboardApiKeyRoute: DashboardApiKeyRoute,
  DashboardEarningsRoute: DashboardEarningsRoute,
  DashboardFilesRoute: DashboardFilesRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSettingsPageRoute: DashboardSettingsPageRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardWithdrawRoute: DashboardWithdrawRoute,
  MainAdminRoute: MainAdminRoute,
  ShareFileIdRoute: ShareFileIdRoute,
  VTokenRoute: VTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AdminUserIdRoute: AdminUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
